-- 유저 테이블
CREATE TABLE TB_USER (
	USER_ID 		 	VARCHAR(20) NOT NULL,
	USER_NAME	 		VARCHAR(10) NOT NULL,
	USER_PASSWORD 	 	VARCHAR(20) NOT NULL,
	BIRTH_DAY 			VARCHAR(8)  NOT NULL,
	GENDER 		 		VARCHAR(2)  NOT NULL,
	POST_NUMBER  		VARCHAR(8)  NOT NULL,
	MAIN_ADDRESS		VARCHAR(50) NOT NULL,
	SUB_ADDRESS 		VARCHAR(50) NOT NULL,
	CONTACT 		 	VARCHAR(11) NOT NULL,
	EMAIL 		 		VARCHAR(30) NOT NULL,
	PHONE 		 	    VARCHAR(11) NOT NULL,
	PRIVACY_STATE_YN    VARCHAR(1) NOT NULL,
	BALNCE 			    INT 	DEFAULT 0 NOT NULL,
	SAVED_MONEY  	    INT  DEFAULT 0 NOT NULL,
	USER_POINT   	    INT  DEFAULT 0 NOT NULL,
	CREATE_DATE 	 TIMESTAMP DEFAULT NOW() NOT NULL,
	LAST_LOGIN_DATE TIMESTAMP DEFAULT NOW() NOT NULL,
	LOGIN_YN	VARCHAR(2) DEFAULT 'N',
	PRIMARY KEY (USER_ID)
) ENGINE=InnoDB DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;

-- 카테고리
CREATE TABLE TB_CATEGORY (
	CATEGORY_ID			VARCHAR(10) NOT NULL,
	CATEGORY_NAME		VARCHAR(20) NOT NULL,
	PARENT_CATEGORY_ID	VARCHAR(10),
	PRIMARY KEY (CATEGORY_ID)
) ENGINE=InnoDB DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;

-- 상품관리
CREATE TABLE TB_ITEM ( 
	ITEM_NAME		VARCHAR(30) NOT NULL,
	CATEGORY_ID		VARCHAR(30) NOT NULL,
	PRICE			INT			NOT NULL,
	DESCRIPTION 	TEXT 			NOT NULL,
	IMAGE			VARCHAR(50)	NOT NULL,
	PRIMARY KEY (ITEM_NAME)		
) ENGINE=InnoDB DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;

-- 재고 관리
CREATE TABLE TB_ITEM_STOCK (
	ITEM_NAME		VARCHAR(30) NOT NULL,
	SIZE 			INT			NOT NULL,
	COLOR			VARCHAR(10) NOT NULL,
	QUANTITY		INT			NOT NULL
) ENGINE=InnoDB DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;


-- 주문 관리
CREATE TABLE TB_ORDER (
	ORDER_ID	VARCHAR(30) NOT NULL,
	USER_ID	VARCHAR(30) NOT NULL,
	ITEM_NAME	VARCHAR(30) NOT NULL,
	ORDER_DATE	TIMESTAMP DEFAULT NOW() NOT NULL,
	QUANTITY		INT	NOT NULL,
	PRIMARY KEY (ORDER_ID)
) ENGINE=InnoDB DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;

-- 장바구니
CREATE TABLE TB_BASKET (
	USER_ID 	VARCHAR(30) NOT NULL,
	ITEM_NAME 	VARCHAR(30) NOT NULL,
	ORDER_DATE 	TIMESTAMP DEFAULT NOW() NOT NULL,
	QUANTITY	INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;

CREATE TABLE TB_COUPON (
	COUPON_ID		VARCHAR(30) NOT NULL,
	ITEM_NAME		VARCHAR(30) NOT NULL,
	COUPON_DETAIL	TEXT	NOT NULL,
	START_DATE		TIMESTAMP DEFAULT NOW() NOT NULL,
	END_DATE		TIMESTAMP DEFAULT NOW() NOT NULL,
	PRIMARY KEY (COUPON_ID)
) ENGINE=InnoDB DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;
